Traceback (most recent call last):
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Control de errores y Debugging: Identifica y corrige el error en el siguiente cÃ³digo, que deberÃ­a calcular el promedio de una lista de nÃºmeros.

def promedio_calificaciones(Calificaciones):
    valores=Calificaciones      
    prom = 0
    for i in valores:
        prom+=i
    fltProm = prom / len(valores)     
    print("Tu promedio es de:",fltProm)   
    print("Calificaciones:",valores) 
   


lstCalificaciones =[10,5,8,9,"10"]
promedio_calificaciones(lstCalificaciones)


------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[9], line 15[0m
[0;32m     10[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCalificaciones:[39m[38;5;124m"[39m,valores) 
[0;32m     14[0m lstCalificaciones [38;5;241m=[39m[[38;5;241m10[39m,[38;5;241m5[39m,[38;5;241m8[39m,[38;5;241m9[39m,[38;5;124m"[39m[38;5;124m10[39m[38;5;124m"[39m]
[1;32m---> 15[0m [43mpromedio_calificaciones[49m[43m([49m[43mlstCalificaciones[49m[43m)[49m

Cell [1;32mIn[9], line 7[0m, in [0;36mpromedio_calificaciones[1;34m(Calificaciones)[0m
[0;32m      5[0m prom [38;5;241m=[39m [38;5;241m0[39m
[0;32m      6[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m valores:
[1;32m----> 7[0m     [43mprom[49m[38;5;241;43m+[39;49m[38;5;241;43m=[39;49m[43mi[49m
[0;32m      8[0m fltProm [38;5;241m=[39m prom [38;5;241m/[39m [38;5;28mlen[39m(valores)     
[0;32m      9[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mTu promedio es de:[39m[38;5;124m"[39m,fltProm)   

[1;31mTypeError[0m: unsupported operand type(s) for +=: 'int' and 'str'

